
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.1.1
    restart: always
    ##net: ${NETWORK}
    container_name: elastic_container
    ports:
      - "9200:9200"
    volumes:
      - ./esdata:/data
      ##- ./elastic/plugins:/plugins
      ##- ./elastic/conf:/usr/share/elasticsearch/config
      ##- ./elastic/scripts:/usr/share/elasticsearch/config/scripts
    #environment:
    #  - discovery.type=single-node

  neo4j:
    restart: always
    image: neo4j:3.5.14
    container_name: neo4j
    links:
      - elastic
    depends_on:
      - elastic
    ##net: ${NETWORK}
    environment:
      - NEO4J_AUTH=none
      - dbms.default_listen_address=0.0.0.0.
     # - elastic="http://elastic_container"
    volumes:
      - ./neo4j/conf:/conf
      - ./neo4j/plugins:/plugins
      - ./neo4j/data/import:/data/import
    ports:
      - "7474:7474"
      - "7687:7687"

